### ISSUE TITLE
this is a hidden gem. thx, tried it with three questions

### ISSUE THREAD

**Issue by kolinfluence** [viant/scache#3]
1. how do i clear the cache? and also clear "mmap" feature. means delete all entries. (sort of need to purge data)
2. i've tried mmap "test" folder, which ran out of memory and signal killed by linux OS. 
thereafter i set the 10mil run to 5mil and it doesnt run out of mem.

how do i ensure that it doesnt run out of mem? this is by entries or mem size specified? just to be doubly sure.

3. is it possible for the mmap to have multiple process reading and writing at the same time? or is it just multi process readable, not writeable at same time?

**Comment by adranwit** [comment]
These are all good questions, 
1. there is currently only entry removal, and cache segment automatically get cleared when segment role switch takes place, please go ahead and contribute more functionality if needed
2.  I guess default test setting could be to aggressive,  currently cache size is estimated based on entry size and max entries or size mb
3. It should be possible since all writes is sequential, and read is lock free,
